//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherForecastWPF_Version_1_0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherForecastWPF_Version_1_0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent Temperature (C).
        /// </summary>
        public static string apparentTemperature {
            get {
                return ResourceManager.GetString("apparentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmospheric pressure (P).
        /// </summary>
        public static string atmosphericPressure {
            get {
                return ResourceManager.GetString("atmosphericPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity (%).
        /// </summary>
        public static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature (C).
        /// </summary>
        public static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string timezone {
            get {
                return ResourceManager.GetString("timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV index.
        /// </summary>
        public static string uvIndex {
            get {
                return ResourceManager.GetString("uvIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Forecast.
        /// </summary>
        public static string weatherForecast {
            get {
                return ResourceManager.GetString("weatherForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast for the next 7 days.
        /// </summary>
        public static string weatherForecastForTheNext {
            get {
                return ResourceManager.GetString("weatherForecastForTheNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed (km/h).
        /// </summary>
        public static string windSpeed {
            get {
                return ResourceManager.GetString("windSpeed", resourceCulture);
            }
        }
    }
}
